// ─── Configuration ─────────────────────────────────────────────────────────

export interface AgentWatchConfig {
  /** Your AgentWatch API key (aw_live_...) */
  apiKey: string;

  /** Base URL of the AgentWatch API. Defaults to https://agentwatch.dev */
  baseUrl?: string;

  /** Whether to enable debug logging. Defaults to false. */
  debug?: boolean;

  /**
   * If true, SDK operates in dry-run mode — traces are built but not sent.
   * Useful for local testing without a real API key.
   */
  dryRun?: boolean;

  /** Maximum number of traces to buffer before sending immediately */
  maxBatchSize?: number;

  /** Periodic flush interval in milliseconds (default: 1000ms) */
  flushIntervalMs?: number;

  /** Maximum retry attempts for failed requests (default: 3) */
  maxRetries?: number;

  /** Initial backoff delay in milliseconds (default: 500ms) */
  retryDelayMs?: number;

  /** Custom fetch implementation for testing or polyfilling */
  fetch?: typeof fetch;
}

export interface TraceOptions {
  /** Optional categorization tags (e.g. ["production", "v2", "customer-tier-pro"]) */
  tags?: string[];

  /** End-user or customer identifier within your application */
  userId?: string;
}

// ─── Trace ─────────────────────────────────────────────────────────────────

export interface TraceContext {
  /** Unique trace ID generated by the SDK */
  id: string;

  /** Start a new LLM span within this trace */
  llm(options: LlmSpanOptions): LlmSpan;

  /** Start a new tool span within this trace */
  tool(name: string, options?: ToolSpanOptions): ToolSpan;

  /** Record an error on this trace */
  error(error: Error | string, options?: ErrorOptions): void;
}

// ─── LLM Span ──────────────────────────────────────────────────────────────

export interface LlmSpanOptions {
  model: string;
  provider?: string;
  temperature?: number;
  /** The full prompt/messages sent to the model (will be stored) */
  request?: unknown;
}

export interface LlmSpanResult {
  inputTokens: number;
  outputTokens: number;
  /** The full model response (will be stored) */
  response?: unknown;
}

export interface LlmSpan {
  /** Call when the LLM call completes */
  end(result: LlmSpanResult): void;
  /** Call if the LLM call failed */
  fail(error: Error | string): void;
}

// ─── Tool Span ─────────────────────────────────────────────────────────────

export interface ToolSpanOptions {
  /** Arguments passed to the tool */
  arguments?: unknown;
}

export interface ToolSpanResult {
  result?: unknown;
  status?: "success" | "failed" | "timeout";
}

export interface ToolSpan {
  end(result?: ToolSpanResult): void;
  fail(error: Error | string): void;
}

// ─── Error Options ─────────────────────────────────────────────────────────

export interface ErrorOptions {
  retryCount?: number;
  wastedCostUsd?: number;
}

// ─── Payload ───────────────────────────────────────────────────────────────

/** The full trace payload sent to the AgentWatch ingestion API */
export interface TracePayload {
  agentName: string;
  status: "success" | "failed" | "timeout";
  startedAt: string;  // ISO 8601
  endedAt: string;    // ISO 8601
  durationMs: number;
  tags?: string[];
  userId?: string;
  steps: StepPayload[];
}

export interface StepPayload {
  stepType: "llm" | "tool" | "error" | "custom";
  sequence: number;
  name?: string;
  startedAt: string;
  endedAt?: string;
  durationMs?: number;
  llmCall?: {
    modelName: string;
    provider?: string;
    inputTokens: number;
    outputTokens: number;
    temperature?: string;
    requestJson?: string;
    responseJson?: string;
  };
  toolCall?: {
    toolName: string;
    status: "success" | "failed" | "timeout";
    argumentsJson?: string;
    resultJson?: string;
  };
  error?: {
    errorType: string;
    message: string;
    stackTrace?: string;
    retryCount?: number;
    wastedCostUsd?: string;
  };
}
